<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="C:\Users\Shahin Lap\Downloads\images\1.jpg" Link="wwwroot\images\1.jpg" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\1.mp4" Link="wwwroot\images\1.mp4" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\logo.png" Link="wwwroot\images\logo.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\placeholder.png" Link="wwwroot\images\placeholder.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\21b5ffa7-4e77-47d7-832f-17c519d5ebfd.png" Link="wwwroot\images\products\21b5ffa7-4e77-47d7-832f-17c519d5ebfd.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_AlAhly_Away_Socks.png" Link="wwwroot\images\products\Adidas_AlAhly_Away_Socks.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_AlAhly_Home_Socks.png" Link="wwwroot\images\products\Adidas_AlAhly_Home_Socks.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Copa_Boots.png" Link="wwwroot\images\products\Adidas_Copa_Boots.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Copa_League_Boots.png" Link="wwwroot\images\products\Adidas_Copa_League_Boots.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_F50League_Boots.png" Link="wwwroot\images\products\Adidas_F50League_Boots.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_FCBayern_Home_Socks.png" Link="wwwroot\images\products\Adidas_FCBayern_Home_Socks.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Liverpool_FCHome_Club_Ball.png" Link="wwwroot\images\products\Adidas_Liverpool_FCHome_Club_Ball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Predator_Firm_Ground_Boots.png" Link="wwwroot\images\products\Adidas_Predator_Firm_Ground_Boots.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Predator_League_Goalkeeper_Gloves.png" Link="wwwroot\images\products\Adidas_Predator_League_Goalkeeper_Gloves.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Predator_League_TurfBoots.png" Link="wwwroot\images\products\Adidas_Predator_League_TurfBoots.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Predator_Training_Goalkeeper_Gloves.png" Link="wwwroot\images\products\Adidas_Predator_Training_Goalkeeper_Gloves.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Socks_3Pairs.png" Link="wwwroot\images\products\Adidas_Socks_3Pairs.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Tiro_Club_Shin_Guards_black&amp;white.png" Link="wwwroot\images\products\Adidas_Tiro_Club_Shin_Guards_black&amp;white.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_Tiro_Club_Shin_Guards_Gold&amp;Metalic.png" Link="wwwroot\images\products\Adidas_Tiro_Club_Shin_Guards_Gold&amp;Metalic.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Adidas_UCL_League_League_Stage_Ball.png" Link="wwwroot\images\products\Adidas_UCL_League_League_Stage_Ball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\AlphaFit_Kettlebells_16Kg.png" Link="wwwroot\images\products\AlphaFit_Kettlebells_16Kg.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Babolat_Tennis_Bag.png" Link="wwwroot\images\products\Babolat_Tennis_Bag.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Blue_NewYork_Jersey.png" Link="wwwroot\images\products\Blue_NewYork_Jersey.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\cf335b9b-18fe-4bd1-9bc0-3519378403ec.png" Link="wwwroot\images\products\cf335b9b-18fe-4bd1-9bc0-3519378403ec.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Element_Kettlebell_24kg.png" Link="wwwroot\images\products\Element_Kettlebell_24kg.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Fitline_Barbell.png" Link="wwwroot\images\products\Fitline_Barbell.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\FitRx_Adjustable_Dumbbells_52.5lb.png" Link="wwwroot\images\products\FitRx_Adjustable_Dumbbells_52.5lb.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Hyrox_Kettlebells_24Kg.png" Link="wwwroot\images\products\Hyrox_Kettlebells_24Kg.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Inspace_Black_Rubber_Kettlebell_6kg.png" Link="wwwroot\images\products\Inspace_Black_Rubber_Kettlebell_6kg.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Jersey_Boston_Celtics_Authentic_Larry_Bird.png" Link="wwwroot\images\products\Jersey_Boston_Celtics_Authentic_Larry_Bird.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Jordan_Cap_midnight_NavyBlackBlue.png" Link="wwwroot\images\products\Jordan_Cap_midnight_NavyBlackBlue.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Kipsta_Allsix_Volleyball_KneePads_Black.png" Link="wwwroot\images\products\Kipsta_Allsix_Volleyball_KneePads_Black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\KIPSTA_Beach_Volleyball_Turquoise.png" Link="wwwroot\images\products\KIPSTA_Beach_Volleyball_Turquoise.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\KIPSTA_UEFA_League_Replica_Football.png" Link="wwwroot\images\products\KIPSTA_UEFA_League_Replica_Football.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Men'sJason_Warriors_Jersey_Navy&amp;Golden.png" Link="wwwroot\images\products\Men%27sJason_Warriors_Jersey_Navy&amp;Golden.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Men_Bulls_Hebru.png" Link="wwwroot\images\products\Men_Bulls_Hebru.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Mizuno_Kneepad_volleyball.png" Link="wwwroot\images\products\Mizuno_Kneepad_volleyball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nba_Jersey_Chicago_Bulls_Michael_Jordan.png" Link="wwwroot\images\products\Nba_Jersey_Chicago_Bulls_Michael_Jordan.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\New_York_Yankees_Cap_black.png" Link="wwwroot\images\products\New_York_Yankees_Cap_black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_AirHuarache_Trainers_whitepure.png" Link="wwwroot\images\products\Nike_AirHuarache_Trainers_whitepure.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_AIRMAX270_Trainers_whiteblack.png" Link="wwwroot\images\products\Nike_AIRMAX270_Trainers_whiteblack.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_BLAZER_Trainers_white.png" Link="wwwroot\images\products\Nike_BLAZER_Trainers_white.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Blazer_white&amp;black.png" Link="wwwroot\images\products\Nike_Blazer_white&amp;black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Dunk_Trainers_Football_tealpearl.png" Link="wwwroot\images\products\Nike_Dunk_Trainers_Football_tealpearl.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Dunk_Trainers_whiteblack.png" Link="wwwroot\images\products\Nike_Dunk_Trainers_whiteblack.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Everyday_Basketball.png" Link="wwwroot\images\products\Nike_Everyday_Basketball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Flight_Soccer_Ball1.png" Link="wwwroot\images\products\Nike_Flight_Soccer_Ball1.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Gym_Sports_bag_black.png" Link="wwwroot\images\products\Nike_Gym_Sports_bag_black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Gym_Sports_bag_lightsilver.png" Link="wwwroot\images\products\Nike_Gym_Sports_bag_lightsilver.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Heritage_Cap_black.png" Link="wwwroot\images\products\Nike_Heritage_Cap_black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Heritage_Cap_elementalGold.png" Link="wwwroot\images\products\Nike_Heritage_Cap_elementalGold.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nike_Utility_Power_Sports_bag_black.png" Link="wwwroot\images\products\Nike_Utility_Power_Sports_bag_black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Nivia_Leather_Volleyball.png" Link="wwwroot\images\products\Nivia_Leather_Volleyball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Peak_Shoes_Basketball_Red.png" Link="wwwroot\images\products\Peak_Shoes_Basketball_Red.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Rubber_Coated_Fixed_Straight_Barbell_40Kg.png" Link="wwwroot\images\products\Rubber_Coated_Fixed_Straight_Barbell_40Kg.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\SG_Enduralite_Lightweight_Cricket_Tennis_Ball.png" Link="wwwroot\images\products\SG_Enduralite_Lightweight_Cricket_Tennis_Ball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\TARMAK_Basketball_BT900.png" Link="wwwroot\images\products\TARMAK_Basketball_BT900.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Urethane_dumbbells_10Kg.png" Link="wwwroot\images\products\Urethane_dumbbells_10Kg.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Volleyball_Arm_Sleeves_black.png" Link="wwwroot\images\products\Volleyball_Arm_Sleeves_black.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Wilson_Basketball.png" Link="wwwroot\images\products\Wilson_Basketball.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Wilson_Tennis_Racket_Blue.png" Link="wwwroot\images\products\Wilson_Tennis_Racket_Blue.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\products\Wilson_WhitePink_Racquet_Tennis_Bag.png" Link="wwwroot\images\products\Wilson_WhitePink_Racquet_Tennis_Bag.png" />
    <Content Include="C:\Users\Shahin Lap\Downloads\images\smlogo.png" Link="wwwroot\images\smlogo.png" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	  <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
	  <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
	  <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GearUp.Infrastructure\GearUp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\images\products\" />
  </ItemGroup>

</Project>
